name: push-main

# 1. Run unit and integration tests
# 2. Push containers to AWS ECR with tag based on incrementing build number
# 3. Recommit an update to the chart's deployments with the updated build number in the `deployment` branch

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'chart/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start DB
        run: docker-compose -f docker-compose.db.yml up -d

      - name: Install requirements
        run: pip3 install -r requirements.txt -r requirements_dev.txt

#      - name: Add workspace to path
#        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Init DB
        run: |
          cd icon_contracts
          alembic upgrade head

      - name: Run tests
        run: python3 -m pytest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr-worker
        uses: aws-actions/amazon-ecr-login@v1

      - name: Worker - Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr-worker.outputs.registry }}
          ECR_REPOSITORY: icon-contracts-worker
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker build --build-arg SERVICE_NAME=api --target prod -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Merge main deployment
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: main
          target_branch: deployment-dev
          github_token: ${{ github.token }}

      - name: Checkout dev deployment
        uses: actions/checkout@v2
        with:
          ref: deployment-dev
          path: deployment-dev

      - name: Update dev-mainnet deployment values file and re-commit
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'chart/deployments/dev-mainnet/values.dev.yaml'
          propertyPath: 'deployment.image.tag'
          value: ${{ github.run_number }}
          branch: deployment-dev
          createPR: 'false'
          message: 'Update dev deployment image version to ${{ github.run_number }}'
          token: ${{ secrets.GITHUB_TOKEN }}
          updateFile: true
          workDir: deployment-dev
